SELECT * FROM claimprac

--LET'S LOOK AT WHAT OUR NORMAL MAX AND MIN RANGES ARE FOR PRICING TO GET AN OVERVIEW OF THE DATA

SELECT 
    MAX(PAYAM) AS 'MAX PAID AMOUNT',
    MIN(PAYAM) AS 'MIN PAID AMOUNT',
    MAX(ALLAM) AS 'MAX ALLOWED AMOUNT',
    MIN(ALLAM) AS 'MIN ALLOWED AMOUNT',
    MAX(BILLAM) AS 'MAX BILLED AMOUNT',
    MIN(BILLAM) AS 'MIN BILLED AMOUNT'
FROM CLAIMPRAC

--DO THESE CLAIMS SHOW REPEATING PROVIDERS/CUSTOMERS OR DO WE HAVE A LARGE VARIETY?
SELECT 
    COUNT(DISTINCT PRVID) AS TotalProviders,
    COUNT(DISTINCT CUSTID) AS TotalCustomers
FROM claimprac;
-- THE DATASET HAS NO REPEATING PROVIDERS/CUSTOMERS


--LETS CATEGORIZE THE AMOUNT DIFFERENCES IN BILLED AMOUNT VERSUS ALLOWED AMOUNT SHOWING 
--THE BILLING DISCREPANCIES WITHIN THE CLAIMS.

IF OBJECT_ID('tempdb..#BillAccuTmp') IS NOT NULL
DROP TABLE #BillAccuTmp

SELECT
    CLMID,
    CASE 
	WHEN SUM(BILLAM- ALLAM) >= 150
	THEN 'CRITICAL OVERBILLING'
	WHEN SUM(BILLAM- ALLAM) >= 100
	THEN 'HIGH OVERBILLING'
	WHEN SUM(BILLAM-ALLAM) >0
	THEN 'MINOR OVERBILLING'
	ELSE 'ACCURATE BILLING'
END AS [BILLING ACCURACY]
INTO #BillAccuTmp
FROM claimprac

    GROUP BY CLMID


-- VIEW THE TEMP TABLE CREATED
SELECT * FROM #BillAccuTmp

-- HOW MANY CLAIMS EXIST WITHIN EACH CATEGORY?

SELECT 
    COUNT(CASE WHEN [BILLING ACCURACY]= 'MINOR OVERBILLING' THEN 1 END) AS MINOR_OVERBILLING_COUNT,
    COUNT(CASE WHEN [BILLING ACCURACY]= 'HIGH OVERBILLING' THEN 1 END) AS HIGH_OVERBILLING_COUNT,
    COUNT(CASE WHEN [BILLING ACCURACY]= 'CRITICAL OVERBILLING' THEN 1 END) AS CRITICAL_OVERBILLING_COUNT,
    COUNT(CASE WHEN [BILLING ACCURACY]= 'ACCURATE BILLING' THEN 1 END) AS ACCURATE_BILLING_COUNT
FROM #BillAccuTmp

--OUT OF 1000 CLAIMS WITH 1000 DIFFERENT PROVIDERS, WE HAVE 6% OF CLAIMS CRITICALLY OVERBILLED AND 19% OF 
--CLAIMS WITH HIGH OVERBILLING. ALL OTHER CLAIMS ARE ONLY MINOR OVERBILLING. 

--ARE THERE ANY OVERPAYMENT CRITICAL ERRORS?

SELECT 
    CLMID,
    ALLAM,
    PAYAM

FROM CLAIMPRAC
WHERE PAYAM > ALLAM

--NO OVERPAID CLAIMS EXIST IN THE DATASET

--WHAT TYPE OF RISK IS INVOLVED WITH EACH CLAIM? WHAT IS THE ROOT CAUSE GROUP? CAN THIS CLAIM OUTCOME BE CHANGED BY FOLLOW UP?

IF OBJECT_ID('tempdb..#RiskBucket') IS NOT NULL
DROP TABLE #RiskBucket

SELECT
CLMID,
CASE
      WHEN CLMST = 'Denied'
        AND BILLAM - ALLAM >= 100
        AND RSNCD LIKE '%authorization%'
      THEN 'High Risk – Financial & Auth'

      WHEN CLMST IN ('Pending','Under Review')
        AND FOLFLG = 'Yes'
      THEN 'Medium Risk – Ops Delay'

      WHEN OUTCM = 'Paid'
        AND BILLAM = ALLAM
      THEN 'Low Risk – Clean Claim'

    ELSE 'Moderate Risk'
END AS Claim_Risk_Tier,
CASE
  WHEN RSNCD LIKE '%eligibility%' THEN 'Eligibility Failure'
  WHEN RSNCD LIKE '%authorization%' THEN 'Authorization Gap'
  WHEN RSNCD LIKE '%billing%' THEN 'Provider Billing Error'
  WHEN RSNCD LIKE '%duplicate%' THEN 'Duplicate Submission'
  ELSE 'Other'
END AS Root_Cause_Group,
CASE
  WHEN FOLFLG = 'Yes' AND OUTCM = 'Denied'
  THEN 'Wasted Follow-Up Effort'
  WHEN FOLFLG = 'No' AND CLMST = 'Denied'
  THEN 'Auto-Denial – No Touch'
  ELSE 'Productive Processing'
END AS Wasted_Effort
INTO #RiskBucket

FROM claimprac
ORDER BY CLMID


---VIEW TABLE

SELECT * FROM #RiskBucket



--Let's look at Overbilling versus risk tier, Root cause, and wasted efforts

SELECT 
    B.CLMID,
    B.[BILLING ACCURACY],
    R.Claim_Risk_Tier,
    R.Root_Cause_Group,
    R.Wasted_Effort
FROM #BillAccuTmp B
JOIN #RiskBucket R
ON B.CLMID = R.CLMID


--Out of these, how many high risk claims do we have? What is the billing accuracy of these claims?

SELECT 
    B.CLMID,
    B.[BILLING ACCURACY],
    R.Claim_Risk_Tier,
    R.Root_Cause_Group,
    R.Wasted_Effort
FROM #BillAccuTmp B
JOIN #RiskBucket R
ON B.CLMID = R.CLMID
WHERE Claim_Risk_Tier like 'High%'

--Which of these claims can we stop from paying until further review?

SELECT 
    B.CLMID,
    B.[BILLING ACCURACY],
    R.Claim_Risk_Tier,
    R.Root_Cause_Group,
    R.Wasted_Effort
FROM #BillAccuTmp B
JOIN #RiskBucket R
ON B.CLMID = R.CLMID
WHERE Claim_Risk_Tier like 'High%'
and Wasted_Effort = 'Productive Processing'


--HOW MANY MONTHS DO WE HAVE CLAIMS FOR IN THIS DATASET AND WHAT MONTHS HAVE THE HIGHEST VOLUME?

SELECT
    YEAR(SSVDT)  AS svc_year,
    MONTH(SSVDT) AS svc_month,
    COUNT(*)     AS total_claims
FROM claimprac
WHERE SSVDT IS NOT NULL
GROUP BY
    YEAR(SSVDT),
    MONTH(SSVDT)
ORDER BY
    svc_year,
    svc_month;


--LET'S BREAK DOWN THOSE TOTALS/RUNNING TOTALS

WITH monthly AS (
    SELECT
        YEAR(SSVDT) AS svc_year,
        MONTH(SSVDT) AS svc_month,
        SUM(PAYAM)   AS month_payam
    FROM claimprac
    GROUP BY
        YEAR(SSVDT),
        MONTH(SSVDT)
)
SELECT
    svc_month,
    month_payam,
    SUM(month_payam) OVER (
        PARTITION BY svc_year
        ORDER BY svc_month
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS running_payam
FROM monthly
ORDER BY
    svc_year,
    svc_month;


--HOW MUCH ARE CUSTOMERS PAYING FOR THEIR CLAIMS? VERSUS THE HEALTH PLAN IN JULY? 
--NOTE: IF WE HAD DISTINCT CUSTOMERS, WE COULD TAKE THIS A STEP FURTHER AND ANALYZE THEM BY USING THE CUSTOMER RUNNING TOTAL BY CUSTOMER
--BUT WITH THIS DATASET WE DO NOT HAVE THAT LUXURY

WITH July AS (
    SELECT
        MONTH(SSVDT) AS svc_month,
        DAY(SSVDT) AS svc_day,
        SUM(PAYAM)   AS healthplanpaid,
        SUM(ALLAM-PAYAM) AS customerpaid
    FROM claimprac
    WHERE MONTH(SSVDT) = 7
    GROUP BY
        MONTH(SSVDT),
        DAY(SSVDT)
)
SELECT 
    svc_month,
    svc_day,
    healthplanpaid,
    SUM(healthplanpaid)
        OVER(
        PARTITION BY svc_month
        ORDER BY svc_day
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS HPrunningtotal,
     customerpaid,
     SUM(customerpaid)
        OVER(
        PARTITION BY svc_month
        ORDER BY svc_day
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUSrunningtotal

FROM JULY



--LET'S NAME SOME PROCEDURES AND CLASSIFY COMPLEXITY LEVELS FOR THOSE PROCEDURES
IF OBJECT_ID('tempdb..#PCDCLASS') IS NOT NULL 
DROP TABLE #PCDCLASS

SELECT 
DISTINCT PCDCD,
CASE WHEN PCDCD IN ('99215','99223','99233')
    THEN 'HIGH'
    WHEN PCDCD IN ('99214','99222','99232')
    THEN 'MODERATE'
    ELSE 'LOW'
    END AS COMPLEXITY_RATE,
CASE 
    WHEN PCDCD IN ('99221','99222','99223') THEN 'Initial hospital care'
    WHEN PCDCD IN ('99231','99232','99233') THEN 'Subsequent hospital care'
    WHEN PCDCD IN ('99213','99214','99215') THEN 'Established patient office/outpatient visit'
    WHEN PCDCD = '99238' THEN 'Hospital discharge day management, 30 minutes or less'
    ELSE 'UNKNOWN'
    END AS PDESCRIPTION
INTO #PCDCLASS
FROM claimprac

--VIEW TABLE
SELECT * FROM #PCDCLASS

--IF WE LOOK AT THE SUM OF THE PAID AMOUNTS BY COMPLEXITY RATE CATEGORY, WHAT ARE WE SPENDING MOST ON?

With Complexity_paid AS (
SELECT 
CLMID,
C.PAYAM as HPPAID,
C.PCDCD AS PCDCD,
P.COMPLEXITY_RATE AS COMPLEXITY_RATE,
P.PDESCRIPTION AS PDESCRIPTION
FROM claimprac C
LEFT JOIN #PCDCLASS P
ON P.PCDCD = C.PCDCD
)
SELECT 
    SUM(HPPAID) AS TOTAL_PAID_AMT,
    CAST(AVG(HPPAID)AS INT) AS AVG_PAID_AMOUNT,
    COUNT(CLMID) AS CLAIM_COUNT,
    COMPLEXITY_RATE
FROM Complexity_paid
GROUP BY COMPLEXITY_RATE

--IT LOOKS LIKE IN TOTAL, LOW COMPLEXITY CLAIMS HAVE THE HIGHEST TOTAL PAID AMOUNT, WE ARE RECIEVING MORE LOW COMPLEXITY CLAIMS THAT 
--ARE AVERAGING THE SAME AMOUNT AS THE HIGH COMPLEXITY CLAIMS 

--THAT WILL END IT FOR MY BROAD ANALYSIS FOR THE CLAIMPRAC DATASET. IF YOU GOT THIS FAR, I HOPE THAT YOU ENJOYED :) 